// consumed in deploy_zklink.js
const DEPLOY_ZKLINK_LOG_PREFIX = 'deploy';
const DEPLOY_LOG_DEPLOYER = 'deployer';
const DEPLOY_LOG_GOVERNOR = 'governor';
const DEPLOY_LOG_ZKLINK_TARGET = 'zkLinkTarget';
const DEPLOY_LOG_ZKLINK_TARGET_VERIFIED = 'zkLinkTargetVerified';
const DEPLOY_LOG_ZKLINK_PROXY = 'zkLinkProxy';
const DEPLOY_LOG_ZKLINK_IS_ETH_GAS_TOKEN = 'isETHGasToken';
const DEPLOY_LOG_ZKLINK_PROXY_VERIFIED = 'zkLinkProxyVerified';
const DEPLOY_LOG_DEPLOY_TX_HASH = 'deployTxHash';
const DEPLOY_LOG_DEPLOY_BLOCK_NUMBER = 'deployBlockNumber';

// consumed in deploy_erc20_bridge.js
const DEPLOY_ERC20_BRIDGE_LOG_PREFIX = 'deploy_erc20_bridge';
const DEPLOY_ERC20_BRIDGE = 'erc20Bridge';
const DEPLOY_ERC20_BRIDGE_VERIFIED = 'erc20BridgeVerified';
const DEPLOY_ERC20_BRIDGE_TARGET = 'erc20BridgeTarget';
const DEPLOY_ERC20_BRIDGE_TARGET_VERIFIED = 'erc20BridgeTargetVerified';

// consumed in deploy_l1_gateway.js or deploy_l2_gateway.js or deploy_eth_gateway.js
const DEPLOY_L1_GATEWAY_LOG_PREFIX = 'deploy_l1_gateway';
const DEPLOY_L2_GATEWAY_LOG_PREFIX = 'deploy_l2_gateway';
const DEPLOY_ETH_GATEWAY_LOG_PREFIX = 'deploy_eth_gateway';
const DEPLOY_GATEWAY = 'gateway';
const DEPLOY_GATEWAY_VERIFIED = 'gatewayVerified';
const DEPLOY_GATEWAY_TARGET = 'gatewayTarget';
const DEPLOY_GATEWAY_TARGET_VERIFIED = 'gatewayTargetVerified';

// consumed in deploy_arbitrator.js
const DEPLOY_ARBITRATOR_LOG_PREFIX = 'deploy_arbitrator';
const DEPLOY_LOG_ARBITRATOR = 'arbitrator';
const DEPLOY_LOG_ARBITRATOR_VERIFIED = 'arbitratorVerified';
const DEPLOY_LOG_ARBITRATOR_TARGET = 'arbitratorTarget';
const DEPLOY_LOG_ARBITRATOR_TARGET_VERIFIED = 'arbitratorTargetVerified';

// consumed in deploy_sync_l2_txHash_relayer.js
const DEPLOY_SYNCL2TXHASHRELAYER_LOG_PREFIX = 'deploy_syncL2TxHashRelayer';
const DEPLOY_LOG_SYNCL2TXHASHRELAYER = 'syncL2TxHashRelayer';
const DEPLOY_LOG_SYNCL2TXHASHRELAYER_VERIFIED = 'syncL2TxHashRelayerVerified';

// consumed in deploy_governance.js
const DEPLOY_GOVERNANCE_LOG_PREFIX = 'deploy_governance';
const DEPLOY_LOG_GOVERNANCE = 'governance';
const DEPLOY_LOG_GOVERNANCE_VERIFIED = 'governanceVerified';

// consumed in deploy_linea_l2_governance.js
const DEPLOY_LINEA_L2_GOVERNANCE_LOG_PREFIX = 'deploy_linea_l2_governance';

// consumed in deploy_zklink_token.js
const DEPLOY_ZKLINK_TOKEN_LOG_PREFIX = 'deploy_zklink_token';
const DEPLOY_LOG_ZKLINK_TOKEN_PROXY = 'zkLinkTokenProxy';
const DEPLOY_LOG_ZKLINK_TOKEN_TARGET = 'zkLinkTokenTarget';
const DEPLOY_LOG_ZKLINK_TOKEN_PROXY_VERIFIED = 'zkLinkTokenProxyVerified';
const DEPLOY_LOG_ZKLINK_TOKEN_TARGET_VERIFIED = 'zkLinkTokenTargetVerified';

module.exports = {
  DEPLOY_ZKLINK_LOG_PREFIX,
  DEPLOY_LOG_DEPLOYER,
  DEPLOY_LOG_GOVERNOR,
  DEPLOY_LOG_ZKLINK_TARGET,
  DEPLOY_LOG_ZKLINK_TARGET_VERIFIED,
  DEPLOY_LOG_ZKLINK_PROXY,
  DEPLOY_LOG_ZKLINK_PROXY_VERIFIED,
  DEPLOY_LOG_ZKLINK_IS_ETH_GAS_TOKEN,
  DEPLOY_LOG_DEPLOY_TX_HASH,
  DEPLOY_LOG_DEPLOY_BLOCK_NUMBER,
  DEPLOY_L1_GATEWAY_LOG_PREFIX,
  DEPLOY_L2_GATEWAY_LOG_PREFIX,
  DEPLOY_ETH_GATEWAY_LOG_PREFIX,
  DEPLOY_GATEWAY,
  DEPLOY_GATEWAY_VERIFIED,
  DEPLOY_GATEWAY_TARGET,
  DEPLOY_GATEWAY_TARGET_VERIFIED,
  DEPLOY_ARBITRATOR_LOG_PREFIX,
  DEPLOY_LOG_ARBITRATOR,
  DEPLOY_LOG_ARBITRATOR_VERIFIED,
  DEPLOY_LOG_ARBITRATOR_TARGET,
  DEPLOY_LOG_ARBITRATOR_TARGET_VERIFIED,
  DEPLOY_ERC20_BRIDGE_LOG_PREFIX,
  DEPLOY_ERC20_BRIDGE,
  DEPLOY_ERC20_BRIDGE_VERIFIED,
  DEPLOY_ERC20_BRIDGE_TARGET,
  DEPLOY_ERC20_BRIDGE_TARGET_VERIFIED,
  DEPLOY_GOVERNANCE_LOG_PREFIX,
  DEPLOY_LOG_GOVERNANCE,
  DEPLOY_LOG_GOVERNANCE_VERIFIED,
  DEPLOY_LINEA_L2_GOVERNANCE_LOG_PREFIX,
  DEPLOY_ZKLINK_TOKEN_LOG_PREFIX,
  DEPLOY_LOG_ZKLINK_TOKEN_PROXY,
  DEPLOY_LOG_ZKLINK_TOKEN_TARGET,
  DEPLOY_LOG_ZKLINK_TOKEN_PROXY_VERIFIED,
  DEPLOY_LOG_ZKLINK_TOKEN_TARGET_VERIFIED,
  DEPLOY_SYNCL2TXHASHRELAYER_LOG_PREFIX,
  DEPLOY_LOG_SYNCL2TXHASHRELAYER,
  DEPLOY_LOG_SYNCL2TXHASHRELAYER_VERIFIED,
};
